import { fotoDoPaciente } from "./fotosPacientes";

/* Dados fictícios da tela de Agendamentos. */

export const metricas = [
  {
    id: "total",
    rotulo: "Total de agendamentos",
    valor: "2.348",
    icone: "calendarioMais",
    nota: "no sistema",
    variacao: { valor: "12%", tendencia: "sobe" },
  },
  {
    id: "confirmados",
    rotulo: "Confirmados",
    valor: "1.842",
    icone: "checkCirculo",
    nota: "agendamentos confirmados",
    tom: "verde",
    variacao: { valor: "15%", tendencia: "sobe" },
  },
  {
    id: "espera",
    rotulo: "Em espera",
    valor: "356",
    icone: "relogio",
    nota: "aguardando confirmação",
    variacao: { valor: "8%", tendencia: "sobe" },
  },
  {
    id: "cancelados",
    rotulo: "Cancelados",
    valor: "150",
    icone: "alertaX",
    nota: "cancelamentos",
    tom: "vermelho",
    variacao: { valor: "3%", tendencia: "sobe" },
  },
];

export const statusAgendamento = {
  confirmado: { rotulo: "Confirmado", variante: "sucesso" },
  espera: { rotulo: "Em espera", variante: "info" },
  retorno: { rotulo: "Retorno", variante: "roxo" },
  cancelado: { rotulo: "Cancelado", variante: "erro" },
  // Chaves do status unificado da API (StatusAgendamento).
  pendente: { rotulo: "Aguardando confirmação", variante: "info" },
  confirmada: { rotulo: "Confirmado", variante: "sucesso" },
  aguardando: { rotulo: "Na recepção", variante: "aviso" },
  em_andamento: { rotulo: "Em atendimento", variante: "info" },
  realizada: { rotulo: "Realizado", variante: "neutro" },
  cancelada: { rotulo: "Cancelado", variante: "erro" },
  faltou: { rotulo: "Não compareceu", variante: "erro" },
};

/** Legenda do calendário. */
export const tiposCalendario = [
  { id: "consultas", rotulo: "Consultas", cor: "var(--azul)" },
  { id: "exames", rotulo: "Exames", cor: "var(--verde-claro)" },
  { id: "retornos", rotulo: "Retornos", cor: "var(--roxo)" },
  { id: "cancelados", rotulo: "Cancelados", cor: "var(--vermelho)" },
];

/** Marcações do mês: dia -> tipos presentes. */
export const marcacoesSetembro = {
  1: ["consultas"],
  2: ["consultas", "exames"],
  3: ["consultas"],
  4: ["exames"],
  5: ["consultas", "retornos"],
  8: ["consultas"],
  9: ["consultas", "exames"],
  10: ["consultas", "exames", "retornos"],
  11: ["consultas"],
  12: ["exames", "cancelados"],
  15: ["consultas", "exames", "retornos"],
  16: ["consultas", "exames"],
  17: ["consultas"],
  18: ["exames", "retornos"],
  19: ["consultas"],
  22: ["consultas"],
  23: ["consultas", "exames"],
  24: ["retornos", "cancelados"],
  25: ["consultas"],
  26: ["exames"],
  29: ["consultas"],
  30: ["consultas", "exames"],
};

export const agendamentos = [
  {
    id: 1,
    data: "15/09/2026",
    hora: "08:00",
    paciente: "Maria Silva Santos",
    foto: fotoDoPaciente("Maria Silva Santos"),
    cpf: "123.456.789-00",
    especialidade: "Clínica Geral",
    profissional: "Dra. Ana Costa",
    crm: "CRM 12345",
    unidade: "Clínica da Família",
    bairro: "Centro",
    status: "confirmado",
  },
  {
    id: 2,
    data: "15/09/2026",
    hora: "09:30",
    paciente: "João Pereira Lima",
    foto: fotoDoPaciente("João Pereira Lima"),
    cpf: "987.654.321-00",
    especialidade: "Pediatria",
    profissional: "Dr. Carlos Mendes",
    crm: "CRM 54321",
    unidade: "Posto de Saúde",
    bairro: "Jaconé",
    status: "espera",
  },
  {
    id: 3,
    data: "15/09/2026",
    hora: "11:00",
    paciente: "Ana Costa Oliveira",
    foto: fotoDoPaciente("Ana Costa Oliveira"),
    cpf: "456.789.123-00",
    especialidade: "Ginecologia",
    profissional: "Dra. Fernanda Rocha",
    crm: "CRM 67890",
    unidade: "Clínica Vida & Saúde",
    bairro: "Sampaio Corrêa",
    status: "confirmado",
  },
  {
    id: 4,
    data: "15/09/2026",
    hora: "14:30",
    paciente: "Carlos Eduardo Mendes",
    foto: fotoDoPaciente("Carlos Eduardo Mendes"),
    cpf: "321.654.987-00",
    especialidade: "Ortopedia",
    profissional: "Dr. Rafael Lima",
    crm: "CRM 98765",
    unidade: "Policlínica Municipal",
    bairro: "Saquarema",
    status: "retorno",
  },
  {
    id: 5,
    data: "16/09/2026",
    hora: "08:15",
    paciente: "Juliana Ferreira Alves",
    foto: fotoDoPaciente("Juliana Ferreira Alves"),
    cpf: "654.321.987-00",
    especialidade: "Cardiologia",
    profissional: "Dr. Marcelo Santos",
    crm: "CRM 11223",
    unidade: "Hospital Municipal",
    bairro: "N. Sra. de Nazareth",
    status: "confirmado",
  },
  {
    id: 6,
    data: "16/09/2026",
    hora: "10:45",
    paciente: "Roberto Almeida Souza",
    foto: fotoDoPaciente("Roberto Almeida Souza"),
    cpf: "789.456.123-00",
    especialidade: "Dermatologia",
    profissional: "Dra. Patrícia Alves",
    crm: "CRM 33445",
    unidade: "Clínica Geral",
    bairro: "Sampaio Corrêa",
    status: "espera",
  },
  {
    id: 7,
    data: "16/09/2026",
    hora: "15:00",
    paciente: "Fernanda Rocha Costa",
    foto: fotoDoPaciente("Fernanda Rocha Costa"),
    cpf: "258.369.147-00",
    especialidade: "Exames Laboratoriais",
    profissional: "Dr. Thiago Martins",
    crm: "CRM 55667",
    unidade: "Centro Médico Praia",
    bairro: "Jaconé",
    status: "cancelado",
  },
  {
    id: 8,
    data: "17/09/2026",
    hora: "09:00",
    paciente: "Lucas Almeida Pinto",
    foto: fotoDoPaciente("Lucas Almeida Pinto"),
    cpf: "147.258.369-00",
    especialidade: "Clínica Geral",
    profissional: "Dra. Ana Costa",
    crm: "CRM 12345",
    unidade: "Clínica da Família",
    bairro: "Centro",
    status: "confirmado",
  },
  {
    id: 9,
    data: "17/09/2026",
    hora: "13:30",
    paciente: "Beatriz Nunes Ramos",
    foto: fotoDoPaciente("Beatriz Nunes Ramos"),
    cpf: "963.852.741-00",
    especialidade: "Pediatria",
    profissional: "Dr. Carlos Mendes",
    crm: "CRM 54321",
    unidade: "UBS de Vilatur",
    bairro: "Vilatur",
    status: "confirmado",
  },
  {
    id: 10,
    data: "18/09/2026",
    hora: "08:45",
    paciente: "Marcos Vinícius Dias",
    foto: fotoDoPaciente("Marcos Vinícius Dias"),
    cpf: "741.852.963-00",
    especialidade: "Oftalmologia",
    profissional: "Dra. Helena Prado",
    crm: "CRM 77889",
    unidade: "Centro de Especialidades",
    bairro: "Saquarema",
    status: "espera",
  },
  {
    id: 11,
    data: "18/09/2026",
    hora: "16:00",
    paciente: "Camila Duarte Freitas",
    foto: fotoDoPaciente("Camila Duarte Freitas"),
    cpf: "159.753.486-00",
    especialidade: "Retorno",
    profissional: "Dr. Rafael Lima",
    crm: "CRM 98765",
    unidade: "Policlínica Municipal",
    bairro: "Saquarema",
    status: "retorno",
  },
  {
    id: 12,
    data: "19/09/2026",
    hora: "10:00",
    paciente: "Paulo Henrique Braga",
    foto: fotoDoPaciente("Paulo Henrique Braga"),
    cpf: "357.159.852-00",
    especialidade: "Clínica Geral",
    profissional: "Dra. Ana Costa",
    crm: "CRM 12345",
    unidade: "ESF Itaúna",
    bairro: "Itaúna",
    status: "confirmado",
  },
];

export const filtrosClinica = [
  { valor: "todas", rotulo: "Todas as clínicas" },
  ...[...new Set(agendamentos.map((a) => a.unidade))].map((u) => ({
    valor: u,
    rotulo: u,
  })),
];

export const filtrosProfissional = [
  { valor: "todos", rotulo: "Todos os profissionais" },
  ...[...new Set(agendamentos.map((a) => a.profissional))].map((p) => ({
    valor: p,
    rotulo: p,
  })),
];
