-- Contas de todos os perfis (PACIENTE, MEDICO, ADMIN).
-- SQL portavel: roda igual no H2 (desenvolvimento) e no PostgreSQL.
CREATE TABLE usuarios (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo VARCHAR(120) NOT NULL,
    email         VARCHAR(180) NOT NULL,
    senha_hash    VARCHAR(100) NOT NULL,
    telefone      VARCHAR(20),
    role          VARCHAR(20)  NOT NULL,
    ativo         BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em     TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT ck_usuarios_role CHECK (role IN ('PACIENTE', 'MEDICO', 'ADMIN'))
);

-- Tokens de redefinicao de senha. Guarda apenas o SHA-256 do token enviado ao usuario.
CREATE TABLE tokens_redefinicao_senha (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT       NOT NULL,
    token_hash VARCHAR(64)  NOT NULL,
    expira_em  TIMESTAMP WITH TIME ZONE NOT NULL,
    usado_em   TIMESTAMP WITH TIME ZONE,
    criado_em  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_tokens_redefinicao_hash UNIQUE (token_hash),
    CONSTRAINT fk_tokens_redefinicao_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX idx_tokens_redefinicao_usuario ON tokens_redefinicao_senha (usuario_id);
